name: "Permission Drift Detector"
description: "Detects risky GitHub Actions workflow permission changes in pull requests"
author: "Meriem Zemane"
branding:
  icon: shield
  color: red

inputs:
  github_token:
    description: "GitHub token to post PR comments"
    required: true
    default: "${{ github.token }}"

runs:
  using: "docker"
  image: "Dockerfile"
